### PR TITLE
Added Issue and pr template

### LINKED ISSUE #1: Add Issue + PR Templates
> ## Description
> Create a custom Issue and Pull Request Template.
> 
> ## Additional Details
> * Make an Issue Template. Any new Contributor must be able to specify if it is a new script or enhancement to an older one. It should also be specified which language he is coding it in.
> * Make a Pull Request Template. Any new Contributor must be able to specify if he has met all the requirements like Clean Code, proper README and Documentation, Screenshots (If any) attached and more.
> 
> You can take inspiration from [here](https://github.com/stevemao/github-issue-templates) and check [this](https://medium.com/better-programming/github-templates-the-smarter-way-to-formalize-pull-requests-among-development-teams-89f8d6a204f) out to know how to achieve the same.

### PR DESCRIPTION
**Pull request by DarshGupta1910**
fix #1

### CODE REVIEW

**Comment by Ayush7614** [comment]
@DarshGupta1910 plss give name like bug_report, script_added this type you can give file name like issue_template

**Comment by Ayush7614** [comment]
image

**Comment by Ayush7614** [comment]
correct your file name

**Comment by Ayush7614** [comment]
image

**Comment by Ayush7614** [comment]
@DarshGupta1910 this time i merged your pull but from next time mention your issue also which you have to fix

**Comment by DarshGupta1910** [comment]
> @DarshGupta1910 this time i merged your pull but from next time mention your issue also which you have to fix

Thank you so much, actually I'm a newbie... will try to improve with time. 😌

**Pull request merged**
